### ISSUE TITLE
attribute margin seems  to be redundant with the wall contour attribute for cyst

### ISSUE THREAD

**Issue by KarlGlaserS** [openimagingdata/CDEStaging#10]
[definitions/upmedic/Cyst.cde.md]

The attribute margin seems  to be redundant with the wall contour attribute. Please decide for one and harmonize the value set. I would prerfer the margin directly conected to cyst!

**Comment by paczos** [comment]
@KarlGlaserS sure, I will update the CDE, so we have only one attribute for that
